package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// ClinkShell handles Clink (CMD with Lua extensions)
type ClinkShell struct{}

func (s *ClinkShell) Name() string {
	return "clink"
}

func (s *ClinkShell) Generate(vars []parser.EnvVar) string {
	return s.GenerateWithKeys(vars, nil)
}

func (s *ClinkShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.GenerateWithOptions(vars, definedKeys, false)
}

func (s *ClinkShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("-- Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("-- Shell: Clink (CMD with Lua)\n")
	sb.WriteString("--\n")
	sb.WriteString("-- To use, create this file: %LOCALAPPDATA%\\clink\\genv.lua\n")
	sb.WriteString("-- With the following content:\n")
	sb.WriteString("--\n")
	sb.WriteString("--   load(io.popen('genv init clink'):read('*a'))()\n")
	sb.WriteString("--\n")
	sb.WriteString("-- Clink will automatically load it on every CMD session.\n\n")

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(clinkDedupeFunction())
		sb.WriteString("\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Clink uses semicolon for PATH-like variables on Windows
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "(os.getenv('"+envVar.Key+"') or '')")
				} else if strings.Contains(expanded, "$") {
					// Build Lua concatenation expression
					processedValues = append(processedValues, buildLuaConcatExpr(expanded))
				} else {
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeLuaString(expanded)))
				}
			}

			value := strings.Join(processedValues, " .. ';' .. ")
			sb.WriteString(fmt.Sprintf("os.setenv('%s', (%s))\n", envVar.Key, value))

			// Add deduplication call if requested and variable is PATH-like
			if dedupePath && isPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("os.setenv('%s', __genv_dedupe_path(os.getenv('%s')))\n", envVar.Key, envVar.Key))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			// Check if contains $VAR references
			if strings.Contains(expanded, "$") {
				luaExpr := buildLuaConcatExpr(expanded)
				sb.WriteString(fmt.Sprintf("os.setenv('%s', %s)\n", envVar.Key, luaExpr))
			} else {
				sb.WriteString(fmt.Sprintf("os.setenv('%s', \"%s\")\n", envVar.Key, escapeLuaString(expanded)))
			}
		}
	}

	return sb.String()
}

func clinkDedupeFunction() string {
	return `-- Function to deduplicate paths
function __genv_dedupe_path(path_string)
    if not path_string then return "" end
    local paths = {}
    local seen = {}
    for path in string.gmatch(path_string, "[^;]+") do
        if not seen[path] then
            seen[path] = true
            table.insert(paths, path)
        end
    end
    return table.concat(paths, ";")
end
`
}

// buildLuaConcatExpr builds a Lua string concatenation expression with os.getenv calls
func buildLuaConcatExpr(s string) string {
	parts := []string{}
	i := 0
	lastIdx := 0

	for i < len(s) {
		if s[i] == '$' && i+1 < len(s) && (isAlphaNum(s[i+1]) || s[i+1] == '_') {
			// Add the string before $VAR
			if i > lastIdx {
				parts = append(parts, fmt.Sprintf("\"%s\"", escapeLuaString(s[lastIdx:i])))
			}

			// Extract variable name
			j := i + 1
			for j < len(s) && (isAlphaNum(s[j]) || s[j] == '_') {
				j++
			}

			varName := s[i+1 : j]
			parts = append(parts, fmt.Sprintf("(os.getenv('%s') or '')", varName))

			i = j
			lastIdx = j
		} else {
			i++
		}
	}

	// Add remaining string
	if lastIdx < len(s) {
		parts = append(parts, fmt.Sprintf("\"%s\"", escapeLuaString(s[lastIdx:])))
	}

	if len(parts) == 0 {
		return "\"\""
	}

	return "(" + strings.Join(parts, " .. ") + ")"
}

func escapeLuaString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}
