package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// CmdShell handles Windows CMD/Batch
type CmdShell struct{}

func (s *CmdShell) Name() string {
	return "cmd"
}

func (s *CmdShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("@echo off\n")
	sb.WriteString("REM Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("REM Shell: CMD/Batch\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// CMD uses semicolon for PATH-like variables
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "%"+envVar.Key+"%")
				} else {
					processedValues = append(processedValues, expanded)
				}
			}
			value := strings.Join(processedValues, ";")
			sb.WriteString(fmt.Sprintf("set \"%s=%s\"\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("set \"%s=%s\"\n", envVar.Key, expanded))
		}
	}

	return sb.String()
}

func (s *CmdShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}
