package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// CmdShell handles Windows CMD/Batch
type CmdShell struct{}

// convertDollarToPercent converts $VAR to %VAR% for CMD syntax
func convertDollarToPercent(s string) string {
	// Replace $KEY pattern with %KEY%
	result := ""
	i := 0
	for i < len(s) {
		if s[i] == '$' && i+1 < len(s) {
			// Found a $, extract the variable name
			j := i + 1
			for j < len(s) && (s[j] >= 'A' && s[j] <= 'Z' || s[j] >= 'a' && s[j] <= 'z' || s[j] >= '0' && s[j] <= '9' || s[j] == '_') {
				j++
			}
			if j > i+1 {
				// Found a variable name
				varName := s[i+1 : j]
				result += "%" + varName + "%"
				i = j
				continue
			}
		}
		result += string(s[i])
		i++
	}
	return result
}

func (s *CmdShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("@echo off\n")
	sb.WriteString("REM Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("REM Shell: CMD/Batch\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// CMD uses semicolon for PATH-like variables
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Convert any remaining $VAR references to %VAR%
				expanded = convertDollarToPercent(expanded)
				processedValues = append(processedValues, expanded)
			}
			value := strings.Join(processedValues, ";")
			sb.WriteString(fmt.Sprintf("set \"%s=%s\"\n", envVar.Key, value))
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			// Convert any remaining $VAR references to %VAR%
			expanded = convertDollarToPercent(expanded)
			sb.WriteString(fmt.Sprintf("set \"%s=%s\"\n", envVar.Key, expanded))
		}
	}

	return sb.String()
}
