package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// CshShell handles C Shell and TCSH
type CshShell struct {
	shellName string
}

func (s *CshShell) Name() string {
	if s.shellName != "" {
		return s.shellName
	}
	return "csh"
}

func (s *CshShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString(fmt.Sprintf("# Shell: %s\n\n", s.Name()))

	for _, envVar := range vars {
		if envVar.IsArray {
			// CSH uses colon-separated values
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					processedValues = append(processedValues, expanded)
				}
			}
			value := strings.Join(processedValues, ":")
			sb.WriteString(fmt.Sprintf("setenv %s \"%s\"\n", envVar.Key, escapeCshString(value)))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("setenv %s \"%s\"\n", envVar.Key, escapeCshString(expanded)))
		}
	}

	return sb.String()
}

func escapeCshString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "!", "\\!")
	return s
}

func (s *CshShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}

func (s *CshShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: C Shell\n\n")

	// Note: csh/tcsh don't have good tools for deduplication
	// We'll just add a comment noting this limitation
	if dedupePath {
		sb.WriteString("# Note: PATH deduplication not implemented for csh/tcsh\n")
		sb.WriteString("# Consider using bash, zsh, or fish for this feature\n\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Join array values with colon for PATH-like variables
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					processedValues = append(processedValues, expanded)
				}
			}
			value := strings.Join(processedValues, ":")
			sb.WriteString(fmt.Sprintf("setenv %s \"%s\"\n", envVar.Key, escapeCshString(value)))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("setenv %s \"%s\"\n", envVar.Key, escapeCshString(expanded)))
		}
	}

	return sb.String()
}
