package shells

import (
	"fmt"
	"runtime"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// ElvishShell handles Elvish shell
type ElvishShell struct{}

func (s *ElvishShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Elvish\n")
	sb.WriteString("#\n")
	sb.WriteString("# Add to ~/.config/elvish/rc.elv:\n")
	sb.WriteString("#   eval (genv init elvish | slurp)\n")
	sb.WriteString("#\n")
	sb.WriteString("# Note: Requires Elvish v0.18+\n\n")

	// Determine path delimiter based on OS (: for Unix, ; for Windows)
	pathDelim := ":"
	if runtime.GOOS == "windows" {
		pathDelim = ";"
	}

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(elvishDedupeFunction())
		sb.WriteString("\n")
	}

	// Build a map of array variables for reference detection
	arrayVars := make(map[string]bool)
	for _, v := range vars {
		if v.IsArray {
			arrayVars[v.Key] = true
		}
	}

	// Track if we've already imported str module
	needsStr := false
	for _, v := range vars {
		if v.IsArray && strings.ToUpper(v.Key) != "PATH" {
			needsStr = true
			break
		}
	}
	if needsStr {
		sb.WriteString("use str\n\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			isPATH := strings.ToUpper(envVar.Key) == "PATH"

			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}

				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					if isPATH {
						processedValues = append(processedValues, "$@paths")
					} else {
						processedValues = append(processedValues, fmt.Sprintf("(str:split %s $E:%s)", pathDelim, envVar.Key))
					}
				} else if strings.HasPrefix(expanded, "$") && !strings.Contains(expanded, "/") {
					// Check if this is a reference to another array variable
					refVar := strings.TrimPrefix(expanded, "$")
					if arrayVars[refVar] {
						// In Elvish, (str:split ...) inside [] automatically spreads
						if isPATH && strings.ToUpper(refVar) == "PATH" {
							processedValues = append(processedValues, "$@paths")
						} else if strings.ToUpper(refVar) == "PATH" {
							// Convert PATH to list elements by splitting
							processedValues = append(processedValues, fmt.Sprintf("(str:split %s (echo $@paths | str:join %s))", pathDelim, pathDelim))
						} else {
							// Spread array environment variable
							processedValues = append(processedValues, fmt.Sprintf("(str:split %s $E:%s)", pathDelim, refVar))
						}
					} else {
						// Single variable reference
						processedValues = append(processedValues, elvishQuote(expanded))
					}
				} else {
					// Quote the value appropriately for Elvish
					processedValues = append(processedValues, elvishQuote(expanded))
				}
			}

			value := strings.Join(processedValues, " ")

			if isPATH {
				// Use $paths for PATH
				sb.WriteString(fmt.Sprintf("set paths = [%s]\n", value))

				// Add deduplication if requested
				if dedupePath {
					sb.WriteString("set paths = [(__genv-dedupe-list $paths)]\n")
				}
			} else {
				// Other array vars: split and join with delimiter
				sb.WriteString(fmt.Sprintf("set E:%s = (str:join %s [%s])\n", envVar.Key, pathDelim, value))

				// Add deduplication if requested and PATH-like
				if dedupePath && IsPathLikeVar(envVar.Key) {
					sb.WriteString(fmt.Sprintf("set E:%s = (str:join %s [(__genv-dedupe-list [(str:split %s $E:%s)])])\n", envVar.Key, pathDelim, pathDelim, envVar.Key))
				}
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}

			sb.WriteString(fmt.Sprintf("set E:%s = %s\n", envVar.Key, elvishQuote(expanded)))
		}
	}
	return sb.String()
}

func elvishDedupeFunction() string {
	return `# Function to deduplicate list items
fn __genv-dedupe-list {|items|
  var seen = [&]
  var result = []
  each {|x|
    if (not (has-key $seen $x)) {
      set seen[$x] = $true
      set result = [$@result $x]
    }
  } $items
  put $@result
}
`
}
