package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// FishShell handles Fish shell
type FishShell struct{}

func (s *FishShell) Name() string {
	return "fish"
}

func (s *FishShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: fish\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// Fish uses space-separated values for arrays
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					// Quote array values in fish
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeFishString(expanded)))
				}
			}
			value := strings.Join(processedValues, " ")
			sb.WriteString(fmt.Sprintf("set -gx %s %s\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("set -gx %s \"%s\"\n", envVar.Key, escapeFishString(expanded)))
		}
	}

	return sb.String()
}

func escapeFishString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

func (s *FishShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}

func (s *FishShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: fish\n\n")

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(fishDedupeFunction())
		sb.WriteString("\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Fish uses space-separated values for arrays
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					// Quote array values in fish
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeFishString(expanded)))
				}
			}
			value := strings.Join(processedValues, " ")
			sb.WriteString(fmt.Sprintf("set -gx %s %s\n", envVar.Key, value))
			
			// Add deduplication call if requested and variable is PATH-like
			if dedupePath && isPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("set -gx %s (__genv_dedupe_path $%s)\n", envVar.Key, envVar.Key))
			}
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("set -gx %s \"%s\"\n", envVar.Key, escapeFishString(expanded)))
		}
	}

	return sb.String()
}

func fishDedupeFunction() string {
	return `# Function to deduplicate paths
function __genv_dedupe_path
    set -l result
    set -l seen
    for item in $argv
        if not contains -- $item $seen
            set -a result $item
            set -a seen $item
        end
    end
    for item in $result
        echo $item
    end
end
`
}
