package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// FishShell handles Fish shell
type FishShell struct{}

func (s *FishShell) Name() string {
	return "fish"
}

func (s *FishShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: fish\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// Fish uses space-separated values for arrays
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					// Quote array values in fish
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeFishString(expanded)))
				}
			}
			value := strings.Join(processedValues, " ")
			sb.WriteString(fmt.Sprintf("set -gx %s %s\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("set -gx %s \"%s\"\n", envVar.Key, escapeFishString(expanded)))
		}
	}

	return sb.String()
}

func escapeFishString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

func (s *FishShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}
