package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// IonShell handles Ion shell
type IonShell struct{}

func (s *IonShell) Name() string {
	return "ion"
}

func (s *IonShell) Generate(vars []parser.EnvVar) string {
	return s.GenerateWithKeys(vars, nil)
}

func (s *IonShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Ion\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// Ion doesn't support arrays for export, use colon-separated strings
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					processedValues = append(processedValues, escapeIonString(expanded))
				}
			}
			value := strings.Join(processedValues, ":")
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, value))
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, escapeIonString(expanded)))
		}
	}

	return sb.String()
}

func escapeIonString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

func (s *IonShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Ion\n\n")

	// Note: Ion has limited array manipulation capabilities
	if dedupePath {
		sb.WriteString("# Note: PATH deduplication not fully implemented for Ion\n")
		sb.WriteString("# Ion has limited array manipulation capabilities\n\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Ion uses array syntax but doesn't export well
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					processedValues = append(processedValues, expanded)
				}
			}
			value := strings.Join(processedValues, ":")
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, expanded))
		}
	}

	return sb.String()
}
