package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// IonShell handles Ion shell
type IonShell struct{}

func (s *IonShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Ion\n\n")

	// Note: Ion has limited array manipulation capabilities
	if dedupePath {
		sb.WriteString("# Note: PATH deduplication not fully implemented for Ion\n")
		sb.WriteString("# Ion has limited array manipulation capabilities\n\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Ion uses array syntax but doesn't export well
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					processedValues = append(processedValues, expanded)
				}
			}
			value := strings.Join(processedValues, ":")
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, expanded))
		}
	}

	return sb.String()
}
