package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// NushellShell handles Nushell
type NushellShell struct{}

func (s *NushellShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Nushell\n")
	sb.WriteString("#\n")
	sb.WriteString("# Usage in env.nu:\n")
	sb.WriteString("#   source ($nu.default-config-dir | path join \"genv.nu\")\n")
	sb.WriteString("#\n\n")

	sb.WriteString("# Export environment variables\n")
	sb.WriteString("export-env {\n")

	// Build a map of array variables for reference detection
	arrayVars := make(map[string]bool)
	for _, v := range vars {
		if v.IsArray {
			arrayVars[v.Key] = true
		}
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Nushell uses list syntax
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "...$env."+envVar.Key)
				} else if strings.HasPrefix(expanded, "$") && !strings.Contains(expanded, "/") {
					// Check if this is a reference to another array variable
					refVar := strings.TrimPrefix(expanded, "$")
					if arrayVars[refVar] {
						// Use spread operator for array references
						processedValues = append(processedValues, "...$env."+refVar)
					} else {
						// Single variable reference - use interpolation
						escaped := escapeNushellString(expanded)
						if strings.Contains(escaped, "$env.") {
							processedValues = append(processedValues, fmt.Sprintf("$\"%s\"", convertToNushellInterpolation(escaped)))
						} else {
							processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escaped))
						}
					}
				} else {
					escaped := escapeNushellString(expanded)
					// If the string contains $env. references, use interpolated string syntax
					if strings.Contains(escaped, "$env.") {
						processedValues = append(processedValues, fmt.Sprintf("$\"%s\"", convertToNushellInterpolation(escaped)))
					} else {
						processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escaped))
					}
				}
			}
			value := strings.Join(processedValues, ", ")

			// Add deduplication inline if requested and variable is PATH-like
			if dedupePath && IsPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("    $env.%s = ([%s] | uniq)\n", envVar.Key, value))
			} else {
				sb.WriteString(fmt.Sprintf("    $env.%s = [%s]\n", envVar.Key, value))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			escaped := escapeNushellString(expanded)
			// If the string contains $env. references, use interpolated string syntax
			if strings.Contains(escaped, "$env.") {
				sb.WriteString(fmt.Sprintf("    $env.%s = $\"%s\"\n", envVar.Key, convertToNushellInterpolation(escaped)))
			} else {
				sb.WriteString(fmt.Sprintf("    $env.%s = \"%s\"\n", envVar.Key, escaped))
			}
		}
	}

	sb.WriteString("}\n")

	return sb.String()
}
