package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// NushellShell handles Nushell
type NushellShell struct{}

func (s *NushellShell) Name() string {
	return "nushell"
}

func (s *NushellShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Nushell\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// Nushell uses list syntax
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "...$env."+envVar.Key)
				} else {
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeNushellString(expanded)))
				}
			}
			value := strings.Join(processedValues, ", ")
			sb.WriteString(fmt.Sprintf("$env.%s = [%s]\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("$env.%s = \"%s\"\n", envVar.Key, escapeNushellString(expanded)))
		}
	}

	return sb.String()
}

func escapeNushellString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

func (s *NushellShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}
