package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// NushellShell handles Nushell
type NushellShell struct{}

func (s *NushellShell) Name() string {
	return "nushell"
}

func (s *NushellShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Nushell\n")
	sb.WriteString("#\n")
	sb.WriteString("# Usage in env.nu:\n")
	sb.WriteString("#   source ($nu.default-config-dir | path join \"genv.nu\")\n")
	sb.WriteString("#\n\n")

	sb.WriteString("# Export environment variables\n")
	sb.WriteString("export-env {\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// Nushell uses list syntax
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "...$env."+envVar.Key)
				} else {
					escaped := escapeNushellString(expanded)
					// If the string contains $env. references, use interpolated string syntax
					if strings.Contains(escaped, "$env.") {
						processedValues = append(processedValues, fmt.Sprintf("$\"%s\"", convertToNushellInterpolation(escaped)))
					} else {
						processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escaped))
					}
				}
			}
			value := strings.Join(processedValues, ", ")
			sb.WriteString(fmt.Sprintf("    $env.%s = [%s]\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			escaped := escapeNushellString(expanded)
			// If the string contains $env. references, use interpolated string syntax
			if strings.Contains(escaped, "$env.") {
				sb.WriteString(fmt.Sprintf("    $env.%s = $\"%s\"\n", envVar.Key, convertToNushellInterpolation(escaped)))
			} else {
				sb.WriteString(fmt.Sprintf("    $env.%s = \"%s\"\n", envVar.Key, escaped))
			}
		}
	}

	sb.WriteString("}\n")

	return sb.String()
}

func escapeNushellString(s string) string {
	// First convert $VAR references to $env.VAR
	s = convertVarRefsToNushell(s)

	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

// convertVarRefsToNushell converts $VAR to $env.VAR format
func convertVarRefsToNushell(s string) string {
	// Handle $VARIABLE references (but not $env. which are already converted)
	if !strings.Contains(s, "$env.") {
		// Match $WORD pattern and convert to $env.WORD
		result := strings.Builder{}
		i := 0
		for i < len(s) {
			if s[i] == '$' && i+1 < len(s) && (isAlphaNum(s[i+1]) || s[i+1] == '_') {
				// Found a variable reference
				result.WriteString("$env.")
				i++ // Skip the $
				// Copy the variable name
				for i < len(s) && (isAlphaNum(s[i]) || s[i] == '_') {
					result.WriteByte(s[i])
					i++
				}
			} else {
				result.WriteByte(s[i])
				i++
			}
		}
		return result.String()
	}
	return s
}

// convertToNushellInterpolation converts a string with $env.VAR to Nushell interpolation format
// The result is meant to be used inside $"(...)", so we wrap each $env.VAR in parens
// For example: "$env.GOPATH\\bin" becomes "($env.GOPATH)\\bin"
func convertToNushellInterpolation(s string) string {
	result := strings.Builder{}
	i := 0

	for i < len(s) {
		if i < len(s)-5 && s[i:i+5] == "$env." {
			// Found $env. reference, wrap it in parentheses
			result.WriteString("($env.")
			i += 5
			// Copy variable name
			for i < len(s) && (isAlphaNum(s[i]) || s[i] == '_') {
				result.WriteByte(s[i])
				i++
			}
			result.WriteString(")")
		} else {
			result.WriteByte(s[i])
			i++
		}
	}

	return result.String()
}

func (s *NushellShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}

func (s *NushellShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Nushell\n")
	sb.WriteString("#\n")
	sb.WriteString("# Usage in env.nu:\n")
	sb.WriteString("#   source ($nu.default-config-dir | path join \"genv.nu\")\n")
	sb.WriteString("#\n\n")

	sb.WriteString("# Export environment variables\n")
	sb.WriteString("export-env {\n")

	// Build a map of array variables for reference detection
	arrayVars := make(map[string]bool)
	for _, v := range vars {
		if v.IsArray {
			arrayVars[v.Key] = true
		}
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Nushell uses list syntax
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "...$env."+envVar.Key)
				} else if strings.HasPrefix(expanded, "$") && !strings.Contains(expanded, "/") {
					// Check if this is a reference to another array variable
					refVar := strings.TrimPrefix(expanded, "$")
					if arrayVars[refVar] {
						// Use spread operator for array references
						processedValues = append(processedValues, "...$env."+refVar)
					} else {
						// Single variable reference - use interpolation
						escaped := escapeNushellString(expanded)
						if strings.Contains(escaped, "$env.") {
							processedValues = append(processedValues, fmt.Sprintf("$\"%s\"", convertToNushellInterpolation(escaped)))
						} else {
							processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escaped))
						}
					}
				} else {
					escaped := escapeNushellString(expanded)
					// If the string contains $env. references, use interpolated string syntax
					if strings.Contains(escaped, "$env.") {
						processedValues = append(processedValues, fmt.Sprintf("$\"%s\"", convertToNushellInterpolation(escaped)))
					} else {
						processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escaped))
					}
				}
			}
			value := strings.Join(processedValues, ", ")

			// Add deduplication inline if requested and variable is PATH-like
			if dedupePath && isPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("    $env.%s = ([%s] | uniq)\n", envVar.Key, value))
			} else {
				sb.WriteString(fmt.Sprintf("    $env.%s = [%s]\n", envVar.Key, value))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			escaped := escapeNushellString(expanded)
			// If the string contains $env. references, use interpolated string syntax
			if strings.Contains(escaped, "$env.") {
				sb.WriteString(fmt.Sprintf("    $env.%s = $\"%s\"\n", envVar.Key, convertToNushellInterpolation(escaped)))
			} else {
				sb.WriteString(fmt.Sprintf("    $env.%s = \"%s\"\n", envVar.Key, escaped))
			}
		}
	}

	sb.WriteString("}\n")

	return sb.String()
}
