package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// PosixShell handles POSIX-compliant shells (sh, bash, zsh, ksh, ash)
type PosixShell struct {
	shellName string
}

func (s *PosixShell) Name() string {
	if s.shellName != "" {
		return s.shellName
	}
	return "posix"
}

func (s *PosixShell) Generate(vars []parser.EnvVar) string {
	return s.GenerateWithKeys(vars, nil)
}

func (s *PosixShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.GenerateWithOptions(vars, definedKeys, false)
}

func (s *PosixShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString(fmt.Sprintf("# Shell: %s\n\n", s.Name()))

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(posixDedupeFunction())
		sb.WriteString("\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Join array values with colon for PATH-like variables
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference (like $PATH)
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, expanded)
				} else {
					processedValues = append(processedValues, quoteIfNeeded(expanded))
				}
			}
			value := strings.Join(processedValues, ":")
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, value))
			
			// Add deduplication call if requested and variable is PATH-like
			if dedupePath && isPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("export %s=\"$(__genv_dedupe_path \"$%s\")\"\n", envVar.Key, envVar.Key))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", envVar.Key, escapeQuotes(expanded)))
		}
	}

	return sb.String()
}

func posixDedupeFunction() string {
	return `# Function to deduplicate colon-separated paths
__genv_dedupe_path() {
    echo "$1" | tr ':' '\n' | awk '!seen[$0]++' | tr '\n' ':' | sed 's/:$//'
}
`
}

func isPathLikeVar(key string) bool {
	upper := strings.ToUpper(key)
	return strings.HasSuffix(upper, "PATH") || strings.HasSuffix(upper, "DIRS")
}

func quoteIfNeeded(s string) string {
	if strings.HasPrefix(s, "$") {
		return s
	}
	return s
}

func escapeQuotes(s string) string {
	return strings.ReplaceAll(s, "\"", "\\\"")
}
