package shells

import (
	"fmt"
	"runtime"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// PowerShell handles PowerShell
type PowerShell struct{}

func (s *PowerShell) Name() string {
	return "powershell"
}

func (s *PowerShell) Generate(vars []parser.EnvVar) string {
	return s.GenerateWithKeys(vars, nil)
}

func (s *PowerShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: PowerShell\n\n")

	// Determine delimiter based on OS
	delimiter := ":"
	if runtime.GOOS == "windows" {
		delimiter = ";"
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "\"${env:"+envVar.Key+"}\"")
				} else {
					processedValues = append(processedValues, "\""+escapePowerShellString(expanded)+"\"")
				}
			}
			// For PATH on Windows, use semicolon; colon for Unix-like
			var arrayDelimiter string
			if strings.ToUpper(envVar.Key) == "PATH" && runtime.GOOS == "windows" {
				arrayDelimiter = ";"
			} else {
				arrayDelimiter = delimiter
			}

			// Join with proper PowerShell syntax: ("item1", "item2") -join ":"
			value := fmt.Sprintf("(%s) -join '%s'", strings.Join(processedValues, ", "), arrayDelimiter)
			sb.WriteString(fmt.Sprintf("$env:%s = %s\n", envVar.Key, value))
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("$env:%s = \"%s\"\n", envVar.Key, escapePowerShellString(expanded)))
		}
	}

	return sb.String()
}

func escapePowerShellString(s string) string {
	// First convert $VAR references to ${env:VAR}
	s = convertVarRefsToPowerShell(s)
	
	s = strings.ReplaceAll(s, "`", "``")
	s = strings.ReplaceAll(s, "\"", "`\"")
	// Don't escape $ if it's part of ${env:...}
	if !strings.Contains(s, "${env:") {
		s = strings.ReplaceAll(s, "$", "`$")
	}
	return s
}

// convertVarRefsToPowerShell converts $VAR to ${env:VAR} format
func convertVarRefsToPowerShell(s string) string {
	// Handle $VARIABLE references (but not ${env:...} which are already converted)
	if !strings.Contains(s, "${env:") {
		// Match $WORD pattern and convert to ${env:WORD}
		for {
			idx := strings.Index(s, "$")
			if idx == -1 {
				break
			}
			
			// Find the end of the variable name
			end := idx + 1
			for end < len(s) && (isAlphaNum(s[end]) || s[end] == '_') {
				end++
			}
			
			if end > idx+1 {
				varName := s[idx+1 : end]
				s = s[:idx] + "${env:" + varName + "}" + s[end:]
			} else {
				break
			}
		}
	}
	return s
}

func isAlphaNum(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')
}

func (s *PowerShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: PowerShell\n\n")

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(powershellDedupeFunction())
		sb.WriteString("\n")
	}

	// Determine delimiter based on OS
	delimiter := ":"
	if runtime.GOOS == "windows" {
		delimiter = ";"
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "\"${env:"+envVar.Key+"}\"")
				} else {
					processedValues = append(processedValues, "\""+escapePowerShellString(expanded)+"\"")
				}
			}
			// For PATH on Windows, use semicolon; colon for Unix-like
			var arrayDelimiter string
			if strings.ToUpper(envVar.Key) == "PATH" && runtime.GOOS == "windows" {
				arrayDelimiter = ";"
			} else {
				arrayDelimiter = delimiter
			}

			// Join with proper PowerShell syntax: ("item1", "item2") -join ":"
			value := fmt.Sprintf("(%s) -join '%s'", strings.Join(processedValues, ", "), arrayDelimiter)
			sb.WriteString(fmt.Sprintf("$env:%s = %s\n", envVar.Key, value))
			
			// Add deduplication call if requested and variable is PATH-like
			if dedupePath && isPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("$env:%s = __genv_dedupe_path $env:%s\n", envVar.Key, envVar.Key))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("$env:%s = \"%s\"\n", envVar.Key, escapePowerShellString(expanded)))
		}
	}

	return sb.String()
}

func powershellDedupeFunction() string {
	return `# Function to deduplicate paths
function __genv_dedupe_path {
    param([string]$PathString)
    $delimiter = if ($IsWindows) { ';' } else { ':' }
    $paths = $PathString -split $delimiter
    $seen = @{}
    $result = @()
    foreach ($path in $paths) {
        if ($path -and -not $seen.ContainsKey($path)) {
            $seen[$path] = $true
            $result += $path
        }
    }
    return $result -join $delimiter
}
`
}
