package shells

import (
	"fmt"
	"runtime"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// PowerShell handles PowerShell
type PowerShell struct{}

func (s *PowerShell) Name() string {
	return "powershell"
}

func (s *PowerShell) Generate(vars []parser.EnvVar) string {
	return s.GenerateWithKeys(vars, nil)
}

func (s *PowerShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: PowerShell\n\n")

	// Determine delimiter based on OS
	delimiter := ":"
	if runtime.GOOS == "windows" {
		delimiter = ";"
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "${env:"+envVar.Key+"}")
				} else {
					processedValues = append(processedValues, escapePowerShellString(expanded))
				}
			}
			// For PATH on Windows, use semicolon; colon for Unix-like
			var arrayDelimiter string
			if strings.ToUpper(envVar.Key) == "PATH" && runtime.GOOS == "windows" {
				arrayDelimiter = ";"
			} else {
				arrayDelimiter = delimiter
			}

			value := strings.Join(processedValues, arrayDelimiter)
			sb.WriteString(fmt.Sprintf("$env:%s = \"%s\"\n", envVar.Key, value))
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("$env:%s = \"%s\"\n", envVar.Key, escapePowerShellString(expanded)))
		}
	}

	return sb.String()
}

func escapePowerShellString(s string) string {
	s = strings.ReplaceAll(s, "`", "``")
	s = strings.ReplaceAll(s, "\"", "`\"")
	// Don't escape $ if it's part of ${env:...} or is a simple $VAR reference
	if !strings.Contains(s, "${env:") && !strings.HasPrefix(s, "$") {
		s = strings.ReplaceAll(s, "$", "`$")
	}
	return s
}
