package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// RcShell handles rc shell (Plan 9 shell)
type RcShell struct{}

func (s *RcShell) Name() string {
	return "rc"
}

func (s *RcShell) Generate(vars []parser.EnvVar) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: rc\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// rc uses space-separated values in parentheses
			var processedValues []string
			for _, val := range envVar.Values {
				expanded := parser.ExpandEnvVar(val, envVar.Key)
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "$"+envVar.Key)
				} else {
					processedValues = append(processedValues, escapeRcString(expanded))
				}
			}
			value := strings.Join(processedValues, " ")
			sb.WriteString(fmt.Sprintf("%s=(%s)\n", envVar.Key, value))
		} else {
			expanded := parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			sb.WriteString(fmt.Sprintf("%s='%s'\n", envVar.Key, escapeRcStringSingle(expanded)))
		}
	}

	return sb.String()
}

func escapeRcString(s string) string {
	// For rc, single quotes within strings need special handling
	if strings.Contains(s, "'") {
		return "'" + strings.ReplaceAll(s, "'", "''") + "'"
	}
	return "'" + s + "'"
}

func escapeRcStringSingle(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

func (s *RcShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	return s.Generate(vars)
}
