package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// XonshShell handles Xonsh shell (Python-based)
type XonshShell struct{}

func (s *XonshShell) Name() string {
	return "xonsh"
}

func (s *XonshShell) Generate(vars []parser.EnvVar) string {
	return s.GenerateWithKeys(vars, nil)
}

func (s *XonshShell) GenerateWithKeys(vars []parser.EnvVar, definedKeys map[string]bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Xonsh\n\n")

	for _, envVar := range vars {
		if envVar.IsArray {
			// Xonsh uses Python-style list syntax
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					// Xonsh uses $VAR for expansion, spread with *
					processedValues = append(processedValues, "*$"+envVar.Key)
				} else {
					processedValues = append(processedValues, fmt.Sprintf("'%s'", escapeXonshString(expanded)))
				}
			}
			value := strings.Join(processedValues, ", ")
			sb.WriteString(fmt.Sprintf("$%s = [%s]\n", envVar.Key, value))
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("$%s = '%s'\n", envVar.Key, escapeXonshString(expanded)))
		}
	}

	return sb.String()
}

func escapeXonshString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}

func (s *XonshShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Xonsh\n\n")

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(xonshDedupeFunction())
		sb.WriteString("\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Xonsh uses Python list syntax
			var processedValues []string
			for _, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					processedValues = append(processedValues, "$"+envVar.Key)
				} else {
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeXonshString(expanded)))
				}
			}
			value := strings.Join(processedValues, ", ")
			sb.WriteString(fmt.Sprintf("$%s = [%s]\n", envVar.Key, value))

			// Add deduplication call if requested and variable is PATH-like
			if dedupePath && isPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("$%s = __genv_dedupe_path($%s)\n", envVar.Key, envVar.Key))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			sb.WriteString(fmt.Sprintf("$%s = \"%s\"\n", envVar.Key, escapeXonshString(expanded)))
		}
	}

	return sb.String()
}

func xonshDedupeFunction() string {
	return `# Function to deduplicate paths
def __genv_dedupe_path(paths):
    seen = set()
    result = []
    for p in paths:
        if p not in seen:
            seen.add(p)
            result.append(p)
    return result
`
}
