package shells

import (
	"fmt"
	"strings"

	"github.com/nattadasu/genv/internal/parser"
)

// XonshShell handles Xonsh shell (Python-based)
type XonshShell struct{}

func (s *XonshShell) GenerateWithOptions(vars []parser.EnvVar, definedKeys map[string]bool, dedupePath bool) string {
	var sb strings.Builder
	sb.WriteString("# Generated by genv - Global Environment Variable Loader\n")
	sb.WriteString("# Shell: Xonsh\n\n")

	// Add deduplication function if requested
	if dedupePath {
		sb.WriteString(xonshDedupeFunction())
		sb.WriteString("\n")
	}

	for _, envVar := range vars {
		if envVar.IsArray {
			// Xonsh uses Python list syntax
			var processedValues []string
			// Check if any value is a self-reference
			hasSelfRef := false
			var selfRefIdx int
			for i, val := range envVar.Values {
				var expanded string
				if definedKeys != nil {
					expanded = parser.ExpandEnvVarWithDefined(val, envVar.Key, definedKeys)
				} else {
					expanded = parser.ExpandEnvVar(val, envVar.Key)
				}
				// Check if this is a self-reference
				if expanded == "$"+envVar.Key {
					hasSelfRef = true
					selfRefIdx = i
					break
				} else {
					processedValues = append(processedValues, fmt.Sprintf("\"%s\"", escapeXonshString(expanded)))
				}
			}

			// Handle self-reference by concatenation
			if hasSelfRef {
				// Build list up to self-reference, then concatenate with existing var
				if len(processedValues) > 0 {
					value := strings.Join(processedValues, ", ")
					sb.WriteString(fmt.Sprintf("$%s = [%s] + $%s\n", envVar.Key, value, envVar.Key))
				}
				// Continue processing remaining values after self-reference
				for i := selfRefIdx + 1; i < len(envVar.Values); i++ {
					var expanded string
					if definedKeys != nil {
						expanded = parser.ExpandEnvVarWithDefined(envVar.Values[i], envVar.Key, definedKeys)
					} else {
						expanded = parser.ExpandEnvVar(envVar.Values[i], envVar.Key)
					}
					sb.WriteString(fmt.Sprintf("$%s = $%s + [\"%s\"]\n", envVar.Key, envVar.Key, escapeXonshString(expanded)))
				}
			} else {
				value := strings.Join(processedValues, ", ")
				sb.WriteString(fmt.Sprintf("$%s = [%s]\n", envVar.Key, value))
			}

			// Add deduplication call if requested and variable is PATH-like
			if dedupePath && IsPathLikeVar(envVar.Key) {
				sb.WriteString(fmt.Sprintf("$%s = __genv_dedupe_path($%s)\n", envVar.Key, envVar.Key))
			}
		} else {
			var expanded string
			if definedKeys != nil {
				expanded = parser.ExpandEnvVarWithDefined(envVar.Values[0], envVar.Key, definedKeys)
			} else {
				expanded = parser.ExpandEnvVar(envVar.Values[0], envVar.Key)
			}
			// Check if the expanded value is a pure variable reference (starts with $ and contains only valid identifier chars)
			if isPureVariableReference(expanded) {
				// Pure variable reference - don't quote it
				sb.WriteString(fmt.Sprintf("$%s = %s\n", envVar.Key, expanded))
			} else if strings.Contains(expanded, "$") {
				// Mixed content with variables - use .format()
				formatStr, formatArgs := convertToXonshFormat(expanded)
				sb.WriteString(fmt.Sprintf("$%s = \"%s\".format(%s)\n", envVar.Key, formatStr, formatArgs))
			} else {
				sb.WriteString(fmt.Sprintf("$%s = '%s'\n", envVar.Key, escapeXonshString(expanded)))
			}
		}
	}

	return sb.String()
}

func xonshDedupeFunction() string {
	return `# Function to deduplicate paths
def __genv_dedupe_path(paths):
    seen = set()
    result = []
    for p in paths:
        if p not in seen:
            seen.add(p)
            result.append(p)
    return result
`
}
